name: Documentation

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install
      run: npm ci

    - name: Run acceptance
      run: npm run acceptance

    - name: Build Acceptance Docs
      run: npm run acceptance:documentation

    # - name: Upload Docs to wiki
    #   uses: cmbrose/github-docs-to-wiki@v0.23
    #   with:
    #     githubToken: ${{secrets.REPO_ACCESS}}
    #     defaultBranch: master
    #     rootDocsFolder: docs
    #     useHeaderForWikiName: false

    # - name: Upload Docs to wiki
    #   uses: SwiftDocOrg/github-wiki-publish-action@v1
    #   with:
    #     path: "docs"
    #   env:
    #     GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS }}
    
    - name: Upload Docs to wiki
      uses: joeizzard/action-wiki-sync@master
      with:
          username: ricardani
          access_token: ${{ secrets.GITHUB_TOKEN }}
          wiki_folder: docs
          commit_username: 'Example Name'
          commit_email: 'github.action@users.noreply.github.com'
