name: Documentation

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install
      run: npm ci

    - name: Run acceptance
      run: npm run acceptance

    - name: Build Acceptance Docs
      run: npm run acceptance:documentation

    - name: Upload Docs to wiki
      run: sh ./tools/action.sh
      with:
          username: ricardani
          access_token: ${{ secrets.GITHUB_TOKEN }}
          wiki_folder: docs
          commit_username: 'Example Name'
          commit_email: 'github.action@users.noreply.github.com'
