name: Documentation

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install
      run: npm ci

    - name: Run acceptance
      run: npm run acceptance

    - name: Build Acceptance Docs
      run: npm run acceptance:documentation

    - name: Upload Docs to wiki
      run: sh ./tools/action.sh
      env:
          ACCESS_TOKEN: ${{ secrets.REPO_ACCESS }}
          WIKI_FOLDER: docs
          COMMIT_USERNAME: 'Example Name'
          COMMIT_EMAIL: 'github.action@users.noreply.github.com'
          COMMIT_MESSAGE: 'Update Wiki'
